import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { MutableRefObject, useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
const inter = Inter({ subsets: ['latin'] })

interface props {
  references: Array<MutableRefObject<null>>
}
const Hero:React.FC<props> = ({references}) =>{
  const handleScroll = (ref:any) => {
    window.scrollTo({
      top: ref.offsetTop,
      left: 0,
      behavior: "smooth",
    });
  };
    const navigation = [
      { name: 'Home', href: '#',onClick: ()=>handleScroll(references[0]) },
        { name: 'Our Commitment', href: '#' ,onClick: ()=>handleScroll(references[1])},
        { name: 'Why work with us', href: '#' ,onClick: ()=>handleScroll(references[2])},
        { name: 'Contact us', href: '#' ,onClick: ()=>handleScroll(references[3])},
       
      ]
      
      const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
    
      
      return (
        <>
          <Head>
            <title>JAVS Construction</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
         
          <div className="isolate bg-white" style={{color:"white"}} ref={references[0]}>
          <div className="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
            <svg
              className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
              viewBox="0 0 1155 678"
            >
              <path
                fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
                fillOpacity=".3"
                d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
              />
              <defs>
                <linearGradient
                  id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
                  x1="1155.49"
                  x2="-78.208"
                  y1=".177"
                  y2="474.645"
                  gradientUnits="userSpaceOnUse"
                >
                  <stop stopColor="#9089FC" />
                  <stop offset={1} stopColor="#FF80B5" />
                </linearGradient>
              </defs>
            </svg>
          </div>
          <div className="px-6 pt-6 lg:px-8">
        
            <nav className="flex items-center justify-between" aria-label="Global">
          
              <div className="flex lg:flex-1">
              <video autoPlay muted loop id="myVideo" className='rounded-xl'>
          <source src="https://firebasestorage.googleapis.com/v0/b/site-9a8dd.appspot.com/o/global%20network%20background%20animation.mp4?alt=media&token=92d13012-5b51-48b9-a30f-6e08e9fba07f" type="video/mp4"/>
          Your browser does not support HTML5 video.
        </video>
                <a href="#" className="-m-1.5 p-1.5">
                  <span className="sr-only">JAVS Construction</span>
               
                </a>
              </div>
              <div className="flex lg:hidden">
                <button
                  type="button"
                  className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                  onClick={() => setMobileMenuOpen(true)}
                >
                  <span className="sr-only">Open main menu</span>
                  <Bars3Icon className="h-6 w-6" aria-hidden="true" />
                </button>
              </div>
              <div className="hidden lg:flex lg:gap-x-12">
                {navigation.map((item) => (
                  <a key={item.name} href={item.href} className="text-sm font-semibold leading-6 text-gray-900" onClick={item.onClick}>
                    {item.name}
                  </a>
                ))}
              </div>
            
            </nav>
            <Dialog as="div" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
              <Dialog.Panel className="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
                <div className="flex items-center justify-between">
                  <a href="#" className="-m-1.5 p-1.5">
                    <span className="sr-only">JAVS Construction</span>
                    <Image className="h-8" src="/logo.png" alt="" width={50} height={50}/>
                  </a>
                  <button
                    type="button"
                    className="-m-2.5 rounded-md p-2.5 text-gray-700"
                    onClick={() => setMobileMenuOpen(false)}
                  >
                    <span className="sr-only">Close menu</span>
                    <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                  </button>
                </div>
                <div className="mt-6 flow-root">
                  <div className="-my-6 divide-y divide-gray-500/10">
                    <div className="space-y-2 py-6">
                      {navigation.map((item) => (
                        <a
                          key={item.name}
                          href={item.href}
                          className="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10"
                          onClick={item.onClick}
                      >
                          {item.name}
                        </a>
                      ))}
                    </div>
                    
                  </div>
                </div>
              </Dialog.Panel>
            </Dialog>
          </div>
          <main>
            <div className="relative px-6 lg:px-8">
              <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
                <div className="hidden sm:mb-8 sm:flex sm:justify-center">
                  {/* <div className="relative rounded-full py-1 px-3 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
                    Announcing our next round of funding.{' '}
                    <a href="#" className="font-semibold text-indigo-600">
                      <span className="absolute inset-0" aria-hidden="true" />
                      Read more <span aria-hidden="true">&rarr;</span>
                    </a>
                  </div> */}
                </div>
                <div className="text-center">
                <Image className="h-8" src="/logo.png" alt="" width={150} height={180} style={{margin:"auto "}}/>
                <br/>
                  <h2 className="text-3xl font-bold tracking-tight text-gray-500 sm:text-4xl"> JAVS Construction </h2>
                  <h1 className="text-4xl font-bold tracking-tight text-white-900 sm:text-6xl">
                    Connecting Communities, Together
                  </h1>
                  <p className="mt-6 text-lg leading-8 text-white-600">
                  At Javs Construction, we believe that access to the internet is a fundamental right, and that every community deserves the opportunity to connect and thrive in the digital age. We bring our passion, expertise, and commitment to excellence to every project, working closely with our clients to connect them to the world.
                  </p>
                  <div className="mt-10 flex items-center justify-center gap-x-6">
                  
                  </div>
                </div>
              </div>
              <div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
                <svg
                  className="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
                  viewBox="0 0 1155 678"
                >
                  <path
                    fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)"
                    fillOpacity=".3"
                    d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
                  />
                  <defs>
                    <linearGradient
                      id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc"
                      x1="1155.49"
                      x2="-78.208"
                      y1=".177"
                      y2="474.645"
                      gradientUnits="userSpaceOnUse"
                    >
                      <stop stopColor="#9089FC" />
                      <stop offset={1} stopColor="#FF80B5" />
                    </linearGradient>
                  </defs>
                </svg>
              </div>
            </div>
          </main>
        </div>
    
        </>
      )

}

export default Hero