import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
import Hero from '../components/hero'
import WorkWithUs from '../components/workwithus'
import CTA from '../components/cta'
import { Features } from '@headlessui/react/dist/utils/render'
import Feature from '../components/feature'
import Footer from '../components/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const navigation = [
    { name: 'Product', href: '#' },
    { name: 'Features', href: '#' },
    { name: 'Marketplace', href: '#' },
    { name: 'Company', href: '#' },
  ]
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <Hero/>
      <Feature/>
      <WorkWithUs/>
      <CTA/>
      <Footer/>
    </>
  )
}
