import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
import Hero from '../components/hero'
import WorkWithUs from '../components/workwithus'
import CTA from '../components/cta'
import { Features } from '@headlessui/react/dist/utils/render'
import Feature from '../components/feature'
import Footer from '../components/footer'
const inter = Inter({ subsets: ['latin'] })
import { useRef } from 'react'
export default function Home() {
  const homeRef = useRef(null); //represents main section
  const commitRef = useRef(null); //represents about section
  const workRef = useRef(null);
  const contactRef = useRef(null);

  
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <Hero references={[homeRef,commitRef, workRef,contactRef]}/>
      <Feature reference={commitRef }/>
      <WorkWithUs reference={workRef}/>
      <CTA reference={contactRef}/>
      <Footer/>
    </>
  )
}
